namespace ThirtyDollarWebsiteConverter
{
    public enum SoundEvent
    {
        VineBoom,
        BruhSoundEffectNumber2,
        Bong,
        Skeleton,
        ReverbClap,
        WhatTheDogDoin,
        CaveNoise,
        Bell,
        Boink,
        ReverbFart,
        Error,
        SkylineNotification,
        MorningFlower,
        Bonk,
        Bleep,
        Alarm,
        IncorrectBuzzer,
        Alert,
        MrKrabsWalking,
        E,
        Number8,
        AyoThePizzaHere,
        Honk,
        GunReload,
        Hitmarker,
        NoiceClick,
        WhistleNotification,
        Gnome,
        RecordScratch,
        Tada,
        Waterphone,
        FryingPan,
        Slip,
        WhipCrack,
        Explosion,
        Oof,
        Subaluwa,
        NecoArc,
        LegoYodaDeath,
        HeHeHeHaw,
        GrandDad,
        MorshuMmm,
        Ding,
        TwentyOne,
        Op,
        Slam,
        DogDancingWeNoSpeakAmericano,
        Coin,
        OneUp,
        SpinJump,
        Stomp,
        KickSuperMarioWorld,
        BossStomp,
        LongJump,
        Damage,
        Bup,
        Thwomp,
        Painting,
        Scream,
        Mario,
        SteelDrum,
        Yoshi,
        Star,
        Flower,
        Gameboy,
        Dog,
        Cat,
        Swan,
        Baby,
        Plane,
        Car,
        Shaker,
        KickRhythmDoctor,
        Hammer,
        TomDrum,
        Sidestick,
        Ride,
        Pop,
        Skipshot,
        OttoEnabled,
        OttoDisabled,
        OttoHappy,
        OttoStressed,
        SoundsTab,
        RowsTab,
        ActionsTab,
        DecorationsTab,
        RoomsTab,
        PreEchoClap,
        Tonk,
        Mistake,
        SamuraiTechno,
        KickADanceOfFireAndIce,
        MidspinClack,
        LevelComplete,
        Cowbell,
        KarateManToss,
        KarateManOffbeatToss,
        KarateManHit,
        KarateManBulb,
        Ook,
        ChorusKid,
        Widget,
        PerfectFailed,
        SkillStar,
        HoennTrumpet,
        ZunPet,
        Left,
        Down,
        Up,
        Right,
        Fail,
        Megalovania,
        MegalovaniaNote,
        Encounter,
        DamageUndertale,
        GameOver,
        Bark,
        Vanish,
        Crash,
        CrashOrbs,
        SecretCoin,
        ManaOrbs,
        Diamond,
        BlastProcessing,
        DamageTheBindingOfIsaac,
        DeathTheBindingOfIsaac,
        HolyMantle,
        Magic,
        Shatter,
        Reforge,
        Move,
        Rule,
        DefeatBabaIsYou,
        Dash,
        DeathCeleste,
        Spring,
        DashGem,
        UltraInstinct,
        Frog,
        AmongUs,
        AmongDrip,
        Amogus,
        NoteBlockHarp,
        NoteBlockBass,
        NoteBlockSnare,
        NoteBlockHat,
        NoteBlockBell,
        NoteBlockChime,
        NoteBlockBanjo,
        NoteBlockPling,
        NoteBlockXylophone,
        NoteBlockBit,
        ExplosionMinecraft,
        BellMinecraft,
        Speed,
        Combine,
        GoToLoop,
        LoopTarget,
        CutAllSounds,
        JumpToTarget,
        SetTarget,
        Pause,
        Volume,
        None
    }

    public static class Sounds
    {
        public static SoundEvent? FromString(string data)
        {
            return data switch
            {
                "last" => SoundEvent.None,
                "!loopmany" => SoundEvent.GoToLoop,
                "!volume" => SoundEvent.Volume,
                "!flash" => SoundEvent.None,
                "!combine" => SoundEvent.Combine,
                "!speed" => SoundEvent.Speed,
                "!looptarget" => SoundEvent.LoopTarget,
                "!loop" => SoundEvent.GoToLoop,
                "!cut" => SoundEvent.CutAllSounds,
                "!target" => SoundEvent.SetTarget,
                "!jump" => SoundEvent.JumpToTarget,
                "_pause" => SoundEvent.Pause,
                "boom" => SoundEvent.VineBoom,
                "bruh" => SoundEvent.BruhSoundEffectNumber2,
                "bong" => SoundEvent.Bong,
                "💀" => SoundEvent.Skeleton,
                "👏" => SoundEvent.ReverbClap,
                "🐶" => SoundEvent.WhatTheDogDoin,
                "👽" => SoundEvent.CaveNoise,
                "🔔" => SoundEvent.Bell,
                "💢" => SoundEvent.Boink,
                "💨" => SoundEvent.ReverbFart,
                "🚫" => SoundEvent.Error,
                "📲" => SoundEvent.SkylineNotification,
                "🌄" => SoundEvent.MorningFlower,
                "🏏" => SoundEvent.Bonk,
                "🤬" => SoundEvent.Bleep,
                "🚨" => SoundEvent.Alarm,
                "buzzer" => SoundEvent.IncorrectBuzzer,
                "❗" => SoundEvent.Alert,
                "🦀" => SoundEvent.MrKrabsWalking,
                "e" => SoundEvent.E,
                "eight" => SoundEvent.Number8,
                "🍕" => SoundEvent.AyoThePizzaHere,
                "🦢" => SoundEvent.Honk,
                "gun" => SoundEvent.GunReload,
                "hitmarker" => SoundEvent.Hitmarker,
                "👌" => SoundEvent.NoiceClick,
                "whatsapp" => SoundEvent.WhistleNotification,
                "gnome" => SoundEvent.Gnome,
                "💿" => SoundEvent.RecordScratch,
                "🎉" => SoundEvent.Tada,
                "🎻" => SoundEvent.Waterphone,
                "pan" => SoundEvent.FryingPan,
                "slip" => SoundEvent.Slip,
                "whipcrack" => SoundEvent.WhipCrack,
                "explosion" => SoundEvent.Explosion,
                "oof" => SoundEvent.Oof,
                "subaluwa" => SoundEvent.Subaluwa,
                "necoarc" => SoundEvent.NecoArc,
                "yoda" => SoundEvent.LegoYodaDeath,
                "hehehehaw" => SoundEvent.HeHeHeHaw,
                "granddad" => SoundEvent.GrandDad,
                "morshu" => SoundEvent.MorshuMmm,
                "stopposting" => SoundEvent.Ding,
                "21" => SoundEvent.TwentyOne,
                "op" => SoundEvent.Op,
                "SLAM" => SoundEvent.Slam,
                "americano" => SoundEvent.DogDancingWeNoSpeakAmericano,
                "smw_coin" => SoundEvent.Coin,
                "smw_1up" => SoundEvent.OneUp,
                "smw_spinjump" => SoundEvent.SpinJump,
                "smw_stomp2" => SoundEvent.Stomp,
                "smw_kick" => SoundEvent.KickSuperMarioWorld,
                "smw_stomp" => SoundEvent.BossStomp,
                "yahoo" => SoundEvent.LongJump,
                "sm64_hurt" => SoundEvent.Damage,
                "bup" => SoundEvent.Bup,
                "thwomp" => SoundEvent.Thwomp,
                "sm64_painting" => SoundEvent.Painting,
                "smm_scream" => SoundEvent.Scream,
                "mariopaint_mario" => SoundEvent.Mario,
                "mariopaint_luigi" => SoundEvent.SteelDrum,
                "smw_yoshi" => SoundEvent.Yoshi,
                "mariopaint_star" => SoundEvent.Star,
                "mariopaint_flower" => SoundEvent.Flower,
                "mariopaint_gameboy" => SoundEvent.Gameboy,
                "mariopaint_dog" => SoundEvent.Dog,
                "mariopaint_cat" => SoundEvent.Cat,
                "mariopaint_swan" => SoundEvent.Swan,
                "mariopaint_baby" => SoundEvent.Baby,
                "mariopaint_plane" => SoundEvent.Plane,
                "mariopaint_car" => SoundEvent.Car,
                "shaker" => SoundEvent.Shaker,
                "🥁" => SoundEvent.KickRhythmDoctor,
                "hammer" => SoundEvent.Hammer,
                "🪘" => SoundEvent.TomDrum,
                "sidestick" => SoundEvent.Sidestick,
                "ride2" => SoundEvent.Ride,
                "buttonpop" => SoundEvent.Pop,
                "skipshot" => SoundEvent.Skipshot,
                "otto_on" => SoundEvent.OttoEnabled,
                "otto_off" => SoundEvent.OttoDisabled,
                "otto_happy" => SoundEvent.OttoHappy,
                "otto_stress" => SoundEvent.OttoStressed,
                "tab_sounds" => SoundEvent.SoundsTab,
                "tab_rows" => SoundEvent.RowsTab,
                "tab_actions" => SoundEvent.ActionsTab,
                "tab_decorations" => SoundEvent.DecorationsTab,
                "tab_rooms" => SoundEvent.RoomsTab,
                "preecho" => SoundEvent.PreEchoClap,
                "tonk" => SoundEvent.Tonk,
                "rdmistake" => SoundEvent.Mistake,
                "samurai" => SoundEvent.SamuraiTechno,
                "adofaikick" => SoundEvent.KickADanceOfFireAndIce,
                "midspin" => SoundEvent.MidspinClack,
                "adofaicymbal" => SoundEvent.LevelComplete,
                "cowbell" => SoundEvent.Cowbell,
                "karateman_throw" => SoundEvent.KarateManToss,
                "karateman_offbeat" => SoundEvent.KarateManOffbeatToss,
                "karateman_hit" => SoundEvent.KarateManHit,
                "karateman_bulb" => SoundEvent.KarateManBulb,
                "ook" => SoundEvent.Ook,
                "choruskid" => SoundEvent.ChorusKid,
                "builttoscale" => SoundEvent.Widget,
                "perfectfail" => SoundEvent.PerfectFailed,
                "🌟" => SoundEvent.SkillStar,
                "hoenn" => SoundEvent.HoennTrumpet,
                "🎺" => SoundEvent.ZunPet,
                "fnf_left" => SoundEvent.Left,
                "fnf_down" => SoundEvent.Down,
                "fnf_up" => SoundEvent.Up,
                "fnf_right" => SoundEvent.Right,
                "fnf_death" => SoundEvent.Fail,
                "megalovania" => SoundEvent.Megalovania,
                "🦴" => SoundEvent.MegalovaniaNote,
                "undertale_encounter" => SoundEvent.Encounter,
                "undertale_hit" => SoundEvent.DamageUndertale,
                "undertale_crack" => SoundEvent.GameOver,
                "toby" => SoundEvent.Bark,
                "gaster" => SoundEvent.Vanish,
                "gdcrash" => SoundEvent.Crash,
                "gdcrash_orbs" => SoundEvent.CrashOrbs,
                "gd_coin" => SoundEvent.SecretCoin,
                "gd_orbs" => SoundEvent.ManaOrbs,
                "gd_diamonds" => SoundEvent.Diamond,
                "bwomp" => SoundEvent.BlastProcessing,
                "isaac_hurt" => SoundEvent.DamageTheBindingOfIsaac,
                "isaac_dead" => SoundEvent.DeathTheBindingOfIsaac,
                "isaac_mantle" => SoundEvent.HolyMantle,
                "terraria_star" => SoundEvent.Magic,
                "terraria_pot" => SoundEvent.Shatter,
                "terraria_reforge" => SoundEvent.Reforge,
                "BABA" => SoundEvent.Move,
                "YOU" => SoundEvent.Rule,
                "DEFEAT" => SoundEvent.DefeatBabaIsYou,
                "celeste_dash" => SoundEvent.Dash,
                "celeste_death" => SoundEvent.DeathCeleste,
                "celeste_spring" => SoundEvent.Spring,
                "celeste_diamond" => SoundEvent.DashGem,
                "ultrainstinct" => SoundEvent.UltraInstinct,
                "flipnote" => SoundEvent.Frog,
                "amongus" => SoundEvent.AmongUs,
                "amongdrip" => SoundEvent.AmongDrip,
                "amogus" => SoundEvent.Amogus,
                "noteblock_harp" => SoundEvent.NoteBlockHarp,
                "noteblock_bass" => SoundEvent.NoteBlockBass,
                "noteblock_snare" => SoundEvent.NoteBlockSnare,
                "noteblock_click" => SoundEvent.NoteBlockHat,
                "noteblock_bell" => SoundEvent.NoteBlockBell,
                "noteblock_chime" => SoundEvent.NoteBlockChime,
                "noteblock_banjo" => SoundEvent.NoteBlockBanjo,
                "noteblock_pling" => SoundEvent.NoteBlockPling,
                "noteblock_xylophone" => SoundEvent.NoteBlockXylophone,
                "noteblock_bit" => SoundEvent.NoteBlockBit,
                "minecraft_explosion" => SoundEvent.ExplosionMinecraft,
                "minecraft_bell" => SoundEvent.BellMinecraft,
                _ => null
            };
        }
    }
}