<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Engine\Sundex.Engine\Sundex.Engine.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\VisualizerScene\VisualizerScene.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Shaders\Taiko\HitBox.frag" />
    <None Remove="Assets\Shaders\Taiko\HitBox.vert" />
    <None Remove="Assets\Shaders\Taiko\Lane.frag" />
    <None Remove="Assets\Shaders\Taiko\Lane.vert" />
  </ItemGroup>

</Project>
