<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Assets\Fonts\Lato-Bold.ttf" />
      <EmbeddedResource Include="Assets\Fonts\Lato-Regular.ttf" />
      <EmbeddedResource Include="Assets\Fonts\README.md" />
      <EmbeddedResource Include="Assets\Fonts\Twemoji.Mozilla.ttf" />
      <EmbeddedResource Include="Assets\Shaders\colored.frag" />
      <EmbeddedResource Include="Assets\Shaders\colored.vert" />
      <EmbeddedResource Include="Assets\Shaders\Playfield\Background\Blip.frag" />
      <EmbeddedResource Include="Assets\Shaders\Playfield\Background\Blip.vert" />
      <EmbeddedResource Include="Assets\Shaders\Playfield\Chunk\Animated.frag" />
      <EmbeddedResource Include="Assets\Shaders\Playfield\Chunk\Animated.vert" />
      <EmbeddedResource Include="Assets\Shaders\Playfield\Chunk\Static.frag" />
      <EmbeddedResource Include="Assets\Shaders\Playfield\Chunk\Static.vert" />
      <EmbeddedResource Include="Assets\Textures\action_icut.png" />
      <EmbeddedResource Include="Assets\Textures\action_missing.png" />
      <EmbeddedResource Include="Assets\Textures\moai.png" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="ManagedBass">
        <HintPath>..\..\..\..\..\.nuget\packages\managedbass\4.0.2\lib\net8.0\ManagedBass.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Converter\ThirtyDollarConverter.Audio\ThirtyDollarConverter.Audio.csproj" />
      <ProjectReference Include="..\..\..\Converter\ThirtyDollarConverter\ThirtyDollarConverter.csproj" />
        <ProjectReference Include="..\..\Engine\ThirtyDollarVisualizer.Engine\ThirtyDollarVisualizer.Engine.csproj" />
    </ItemGroup>

</Project>
