using ThirtyDollarVisualizer.Engine.Renderer.Abstract;
using ThirtyDollarVisualizer.Engine.Renderer.Abstract.Extensions;
using ThirtyDollarVisualizer.Engine.Renderer.Cameras;
using ThirtyDollarVisualizer.Engine.Renderer.Enums;
using ThirtyDollarVisualizer.Engine.Text;
using ThirtyDollarVisualizer.Helpers.Positioning;

namespace ThirtyDollarVisualizer.Scenes.Application;

public class ApplicationTextContainer
{
    private const int UpdatableTextSliceMaxLength = 1024;
    private readonly TextBuffer _controlsBuffer;
    private readonly TextBuffer _debugBuffer;
    private readonly ApplicationFonts _fonts;
    private readonly TextBuffer _genericBuffer;
    private readonly TextBuffer _greetingBuffer;
    private readonly float _scale;

    private readonly string _version;
    private readonly TextBuffer _versionBuffer;

    public ApplicationTextContainer(ApplicationFonts fonts, string version, int width, int height, float scale = 1f)
    {
        Overlay = new Lazy<Layout>(() => CreateLayout(width, height));

        _fonts = fonts;
        _version = version;
        _scale = scale;

        _genericBuffer = new TextBuffer(fonts.LatoBoldProvider);
        _debugBuffer = new TextBuffer(fonts.LatoBoldProvider);
        _greetingBuffer = new TextBuffer(fonts.LatoBoldProvider);
        _versionBuffer = new TextBuffer(fonts.LatoBoldProvider);
        _controlsBuffer = new TextBuffer(fonts.LatoBoldProvider);
        Greeting = _greetingBuffer.GetTextSlice(" ", UpdatableTextSliceMaxLength);
    }

    public Lazy<Layout> Overlay { get; }
    public TextSlice Greeting { get; }
    public bool ShowDebug { get; set; }
    public bool ShowControls { get; set; } = true;
    public bool ShowVersion { get; set; } = true;

    private Layout CreateLayout(int width, int height)
    {
        var overlay = new Layout(width, height);
        overlay.Add("version",
            () => _versionBuffer.GetTextSlice(
                    $"""
                     Don't use the audio generated by this
                     visualizer for a video, as it isn't
                     accurate at the moment. Use the
                     Thirty Dollar Converter instead.

                     Check regularly for updates at:
                     https://github.com/t1stm/ThirtyDollarTools

                     Current Version: {_version}
                     """,
                    (value, buffer, range) => new TextSlice(buffer, range)
                    {
                        Value = value,
                        FontSize = 14 * _scale
                    })
                .WithPosition((10, height, 0), PositionAlign.Bottom | PositionAlign.Left),
            onResize:
            (text, _, h) => { text.SetPosition((10, h, 0), PositionAlign.Bottom | PositionAlign.Left); });

        overlay.Add("controls",
            () => _controlsBuffer.GetTextSlice(
                """
                All controls:

                Scroll -> Scroll up / down.
                Ctrl+Scroll -> Change the zoom.
                Up / Down -> Control the application's volume.
                Left / Right -> Seek the sequence.
                R -> Reload the current sequence.
                C -> Change the camera modes.
                F -> Toggle between fullscreen and windowed.
                Space -> Pause / resume the sequence.
                Escape -> Close the program.
                0-9 -> Seek to bookmark.
                Ctrl+0-9 -> Set bookmark to current time.
                Ctrl+Shift+0-9 -> Clear given bookmark time.
                Ctrl+D -> Show debugging info.
                Page Up/Down -> Seek to previous/next sequence.

                """,
                (value, buffer, range) => new TextSlice(buffer, range)
                {
                    Value = value,
                    FontSize = 14 * _scale,
                    Position = (10, 30, 0)
                }));

        overlay.Add("debug",
            () => _debugBuffer.GetTextSlice(
                "123456789QWERTYUIOPASDFGHJKLZXCVBNM,./;[]'\"-=_+!@#$%^&*()|{}:><?~`qwertyuiopasdfghjklzxcvbnm",
                // TODO: THIS IS A HACK. REALTIME TEXT GENERATION IS BUGGY AT THE MOMENT
                UpdatableTextSliceMaxLength),
            text =>
            {
                text.FontSize = 14 * _scale;
                text.Position = (10, 30, 0);
            }
        );

        overlay.Add("log",
            () => _genericBuffer.GetTextSlice(" ", UpdatableTextSliceMaxLength),
            text =>
            {
                text.FontSize = 48f * _scale;
                text.Position = (20, 20, 0);
            });

        overlay.Add("update", () => _genericBuffer.GetTextSlice(" ", UpdatableTextSliceMaxLength),
            text => { text.SetPosition((10, 0, 0)); });

        return overlay;
    }

    public void RenderStaticText(Camera camera)
    {
        _genericBuffer.RenderBuffer(camera);

        if (ShowDebug)
            _debugBuffer.RenderBuffer(camera);
        if (ShowControls)
            _controlsBuffer.RenderBuffer(camera);
        if (ShowVersion)
            _versionBuffer.RenderBuffer(camera);
    }

    public void RenderGreeting(Camera camera)
    {
        _greetingBuffer.RenderBuffer(camera);
    }

    public T Get<T>(ReadOnlySpan<char> name) where T : IPositionable
    {
        return Overlay.Value.Get<T>(name);
    }
}