<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sunder.Markup</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sundex.Components\Sundex.Components.csproj"/>
    <ProjectReference Include="..\Style DSL\Sundex.Style.DSL\Sundex.Style.DSL.csproj"/>
  </ItemGroup>

</Project>
