<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Sundex.Components</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Scenes\Shared\Shared.csproj"/>
    </ItemGroup>

</Project>
