<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sundex.Components\Sundex.Components.csproj"/>
    <ProjectReference Include="..\Engine\Sundex.Engine\Sundex.Engine.csproj"/>
    <ProjectReference Include="..\Scenes\EditorScene\EditorScene.csproj"/>
    <ProjectReference Include="..\Scenes\HomeScene\HomeScene.csproj"/>
    <ProjectReference Include="..\Scenes\LoadingScene\LoadingScene.csproj"/>
    <ProjectReference Include="..\Scenes\Shared\Shared.csproj"/>
    <ProjectReference Include="..\Scenes\VisualizerScene\VisualizerScene.csproj"/>
  </ItemGroup>

</Project>
