<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8"/>
        <PackageReference Include="Serilog" Version="4.3.1"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Converter\ThirtyDollarConverter\ThirtyDollarConverter.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Sequences\particle-accelerator.🗿"/>
        <EmbeddedResource Include="Sequences\sounds.🗿"/>
        <None Remove="Sequences\another.🗿"/>
        <EmbeddedResource Include="Sequences\another.🗿"/>
    </ItemGroup>

</Project>
